---
- name: Deploy application
  hosts: app
  become: true
  vars:
    user: "{{ user }}"
  tasks:
    - name: Install git on app server
      apt:
        name: git
        state: present

    - name: Fetch the latest version of application code
      git:
        repo: "https://github.com/express42/reddit.git"
        dest: "/home/{{ user }}/reddit"
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ user }}/reddit"

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
