---
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: 0644
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/{{ user }}/db_config
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: enable puma
  systemd: name=puma enabled=yes
